QualitasEnergy/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;

namespace QualitasEnergy.Controllers
{
    public class UsersController : ApiController
    {
        [System.Web.Http.HttpGet]
        public ActionResult<IEnumerable<LoginUser>> GetUsers()
        {
            using (QualitasEnergyEntities context = new QualitasEnergyEntities())
            {
                IQueryable<LoginUser> qualitasQuery = from qualit in context.LoginUser
                                                      orderby qualit.ID ascending
                                                      select qualit;
                return qualitasQuery.ToList();
            }
        }
    }
}

QualitasEnergy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - Qualitas Energy</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <nav style="display: none; margin-bottom: 20px;" id="layoutMain" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Qualitas Data", "Projects", "UserLogin", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Projects Page", "Projects", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Users Page", "Users", "UserLogin", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
            @Html.ActionLink("Logout", "Logout", "UserLogin", new { area = "" }, new { @class = "btn btn-primary" })
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jonathan Del Pino Lomas for Qualitas Energy</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>